version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.26
    restart: always
    ports:
      - "$PRISMA_PORT:$PRISMA_PORT"
    environment:
      PRISMA_CONFIG: |
        port: $PRISMA_PORT
        managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
        databases:
          default:
            connector: mongo
            uri: mongodb://$MONGO_USER:$MONGO_PASS@mongo
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - "$MONGO_PUBLIC_PORT:$MONGO_DOCKER_PORT"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
